[package]
name = "hello-pulsar"
version = "0.1.0"
edition = "2021"


[dependencies]
futures = "0.3"
pulsar = "6.0"
tokio = { version = "1.32", features = ["full"] }

serde_json = "1.0"
env_logger = { version = "0.10", features = [] }
log = "0.4"
